# Project Information
site_name: 心水 - wy 笔记
site_description: wy的个人博客
site_author: wy
site_url: https://jlwy.ml

# Repository
repo_name: 'wangyin77/wangyin77.github.io'
repo_url: 'https://github.com/wangyin77/wangyin77.github.io'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2020 WY'

# Contents
nav:
  - Home: index.md

  - Blog:
    - WSL2 踩坑全记录: blog/WSL2.md
    - Autoware 安装流程记录: blog/Autoware.md

  - Practice:
    - Leetcode:
      - 周赛:
        - 221周:
          - Leetcode_5637. 判断字符串的两半是否相似: lc/Leetcode_5637.md
          - Leetcode_5638. 吃苹果的最大数目: lc/Leetcode_5638.md
          - Leetcode_5210. 球会落何处: lc/Leetcode_5210.md
          - Leetcode_5640. 与数组中元素的最大异或值: lc/Leetcode_5640.md
        - 222周:
          - Leetcode_1710. 卡车上的最大单元数: lc/Leetcode_1710.md
          - Leetcode_1711. 大餐计数: lc/Leetcode_1711.md
          - Leetcode_1712. 将数组分成三个子数组的方案数: lc/Leetcode_1712.md
      - 顺序:
        - Leetcode_1. 两数之和: lc/Leetcode_1.md
        - Leetcode_2. 两数相加: lc/Leetcode_2.md
        - Leetcode_3. 无重复字符的最长子串: lc/Leetcode_3.md
        - Leetcode_4. 寻找两个正序数组的中位数: lc/Leetcode_4.md
        - Leetcode_5. 最长回文子串: lc/Leetcode_5.md
        - Leetcode_6. Z 字形变换: lc/Leetcode_6.md
        - Leetcode_7. 整数反转: lc/Leetcode_7.md
        - Leetcode_8. 字符串转换整数 (atoi): lc/Leetcode_8.md
        - Leetcode_9. 回文数: lc/Leetcode_9.md
        - Leetcode_10. 正则表达式匹配: lc/Leetcode_10.md
        - Leetcode_31. 下一个排列: lc/Leetcode_31.md
        - Leetcode_32. 最长有效括号: lc/Leetcode_32.md
        - Leetcode_33. 搜索旋转排序数组: lc/Leetcode_33.md
        - Leetcode_34. 在排序数组中查找元素的第一个和最后一个位置: lc/Leetcode_34.md
        - Leetcode_35. 搜索插入位置: lc/Leetcode_35.md
        - Leetcode_36. 有效的数独: lc/Leetcode_36.md
        - Leetcode_37. 解数独: lc/Leetcode_37.md
        - Leetcode_38. 外观数列: lc/Leetcode_38.md
        - Leetcode_39. 组合总和: lc/Leetcode_39.md
        - Leetcode_40. 组合总和 II: lc/Leetcode_40.md
    - Basic: 
      - 第一讲 基础算法: basic/basic_algorithm.md
      - 第二讲 数据结构: basic/data structure.md
      - 第三讲 搜索与图论: basic/search.md


  - Interview:
    - 设计模式: interview/设计模式.md
    - 数据结构: interview/数据结构与算法.md
    - 操作系统: interview/操作系统.md
    - 计算机网络: interview/计算机网络.md
    
# Theme
theme:
  icon:
    logo: material/bulma
    repo: fontawesome/brands/github-alt
  name: material
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    scheme: slate
    primary: cyan
    accent: yellow
  include_search_page: false
  search_index_only: false

  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - toc.integrate
  font:
    text: 'Roboto'
    code: 'Inconsolata'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: github.com/wangyin77/
  disqus: wybi-ji

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde