# Project Information
site_name: 心水 - wy 笔记
site_description: wy的个人博客
site_author: wy
site_url: https://jlwy.ml

# Repository
repo_name: 'wangyin77/wangyin77.github.io'
repo_url: 'https://github.com/wangyin77/wangyin77.github.io'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2020 CTF WY'

# Contents
nav:
  - Home: index.md
  - Basic: 
    - 第一讲 基础算法: basic/basic_algorithm.md
    - 第二讲 数据结构: basic/data structure.md
    - 第三讲 搜索与图论: basic/search.md
  - Leetcode:
    - Leetcode_1. 两数之和: lc/Leetcode_1.md
    - Leetcode_2. 两数相加: lc/Leetcode_2.md
    - Leetcode_3. 无重复字符的最长子串: lc/Leetcode_3.md
    - Leetcode_4. 寻找两个正序数组的中位数: lc/Leetcode_4.md
    - Leetcode_5. 最长回文子串: lc/Leetcode_5.md
    - Leetcode_6. Z 字形变换: lc/Leetcode_6.md
    - Leetcode_7. 整数反转: lc/Leetcode_7.md
    - Leetcode_8. 字符串转换整数 (atoi): lc/Leetcode_8.md
    - Leetcode_9. 回文数: lc/Leetcode_9.md
    - Leetcode_10. 正则表达式匹配: lc/Leetcode_10.md
    - Leetcode_31. 下一个排列: lc/Leetcode_31.md
    - Leetcode_32. 最长有效括号: lc/Leetcode_32.md
    - Leetcode_33. 搜索旋转排序数组: lc/Leetcode_33.md
    - Leetcode_34. 在排序数组中查找元素的第一个和最后一个位置: lc/Leetcode_34.md
    - Leetcode_35. 搜索插入位置: lc/Leetcode_35.md

# Theme
theme:
  icon:
    logo: material/bulma
  name: material
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    scheme: slate
    primary: cyan
    accent: pink
  include_search_page: false
  search_index_only: false

  features:
    - navigation.tabs
  font:
    text: '经典宋体简'
    code: 'Inconsolata'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
  disqus: wybi-ji

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ⚓︎
      toc_depth: 0
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde