# Project Information
site_name: 心水 - wy 笔记
site_description: wy的个人博客
site_author: wy
site_url: https://jlwy.ml

# Contents
nav:
  - Home: 
    - Intro: index.md
  - Basic: 
    - 第一讲 基础算法: basic/basic_algorithm.md
    - 第二讲 数据结构: basic/data structure.md
    - 第三讲 搜索与图论: basic/search.md
  - Leetcode:
    - Leetcode_1. 两数之和: lc/Leetcode_1.md
    - Leetcode_2. 两数相加: lc/Leetcode_2.md
    - Leetcode_3. 无重复字符的最长子串: lc/Leetcode_3.md
    - Leetcode_4. 寻找两个正序数组的中位数: lc/Leetcode_4.md
    - Leetcode_5. 最长回文子串: lc/Leetcode_5.md
    - Leetcode_6. Z 字形变换: lc/Leetcode_6.md
    - Leetcode_7. 整数反转: lc/Leetcode_7.md
    - Leetcode_8. 字符串转换整数 (atoi): lc/Leetcode_8.md
    - Leetcode_9. 回文数: lc/Leetcode_9.md
    - Leetcode_10. 正则表达式匹配: lc/Leetcode_10.md
    - Leetcode_31. 下一个排列: lc/Leetcode_31.md
    - Leetcode_32. 最长有效括号: lc/Leetcode_32.md
    - Leetcode_33. 搜索旋转排序数组: lc/Leetcode_33.md
    - Leetcode_34. 在排序数组中查找元素的第一个和最后一个位置: lc/Leetcode_34.md
    - Leetcode_35. 搜索插入位置: lc/Leetcode_35.md

# Theme
theme:
  name: material
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  include_search_page: false
  search_index_only: false

  feature:
#    tabs: true
#    - tabs
    - navigation.tabs
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

extra:
  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - '_static/js/extra.js?v=16'
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css?v=13'